/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as StandardLibraryRouteImport } from './routes/standard-library'
import { Route as TargetsRouteImport } from './routes/targets'
import { Route as WebRouteImport } from './routes/web'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardLibraryRoute = StandardLibraryRouteImport.update({
  id: '/standard-library',
  path: '/standard-library',
  getParentRoute: () => rootRouteImport,
} as any)
const TargetsRoute = TargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => rootRouteImport,
} as any)
const WebRoute = WebRouteImport.update({
  id: '/web',
  path: '/web',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/download': typeof DownloadRoute
  '/language': typeof LanguageRoute
  '/learn': typeof LearnRoute
  '/roadmap': typeof RoadmapRoute
  '/standard-library': typeof StandardLibraryRoute
  '/targets': typeof TargetsRoute
  '/web': typeof WebRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/download': typeof DownloadRoute
  '/language': typeof LanguageRoute
  '/learn': typeof LearnRoute
  '/roadmap': typeof RoadmapRoute
  '/standard-library': typeof StandardLibraryRoute
  '/targets': typeof TargetsRoute
  '/web': typeof WebRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/download': typeof DownloadRoute
  '/language': typeof LanguageRoute
  '/learn': typeof LearnRoute
  '/roadmap': typeof RoadmapRoute
  '/standard-library': typeof StandardLibraryRoute
  '/targets': typeof TargetsRoute
  '/web': typeof WebRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/download'
    | '/language'
    | '/learn'
    | '/roadmap'
    | '/standard-library'
    | '/targets'
    | '/web'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/download'
    | '/language'
    | '/learn'
    | '/roadmap'
    | '/standard-library'
    | '/targets'
    | '/web'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/download'
    | '/language'
    | '/learn'
    | '/roadmap'
    | '/standard-library'
    | '/targets'
    | '/web'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  DownloadRoute: typeof DownloadRoute
  LanguageRoute: typeof LanguageRoute
  LearnRoute: typeof LearnRoute
  RoadmapRoute: typeof RoadmapRoute
  StandardLibraryRoute: typeof StandardLibraryRoute
  TargetsRoute: typeof TargetsRoute
  WebRoute: typeof WebRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standard-library': {
      id: '/standard-library'
      path: '/standard-library'
      fullPath: '/standard-library'
      preLoaderRoute: typeof StandardLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/targets': {
      id: '/targets'
      path: '/targets'
      fullPath: '/targets'
      preLoaderRoute: typeof TargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web': {
      id: '/web'
      path: '/web'
      fullPath: '/web'
      preLoaderRoute: typeof WebRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  DownloadRoute: DownloadRoute,
  LanguageRoute: LanguageRoute,
  LearnRoute: LearnRoute,
  RoadmapRoute: RoadmapRoute,
  StandardLibraryRoute: StandardLibraryRoute,
  TargetsRoute: TargetsRoute,
  WebRoute: WebRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
